Add a traject setting that allows the component identifiers to be configured
projectblacklight/arclight pull request #1317
Opened 2022-11-11 20:36 UTC by cbeer

2022-11-11 22:27 UTC, jcoyne commented
This seems like a good change. 👍

2022-11-11 23:34 UTC, seanaery commented
I like it! Thanks for the quick work on this issue.

2022-12-02 22:44 UTC, jcoyne requested changes

2022-12-02 22:44 UTC, jcoyne commented on lib/arclight/traject/ead2_config.rb
> +  # provide 'component_identifier_format', '%{root_id}%{ref_id}'
Cruft?

2022-12-02 22:44 UTC, jcoyne commented on lib/arclight/traject/ead2_component_config.rb
> +  next if context.output_hash['id']
What is this for? Can it have some documentation?

2022-12-02 22:44 UTC, jcoyne commented on lib/arclight/traject/ead2_component_config.rb
> +  next if context.output_hash['ref_ssi']
What is this for? Can it have some documentation?

2023-12-14 15:23 UTC, marlo-longley commented
The work in this PR was captured in #1478.

2023-12-14 15:23 UTC, closed without merging