Test against a known blacklight release
projectblacklight/arclight pull request #1396
Opened 2023-02-01 18:57 UTC by cbeer

2023-02-01 18:58 UTC, jcoyne approved these changes

2023-02-01 18:59 UTC, jcoyne requested changes
This causes the non-matrix build to run with BL 7.33, which will fail.

2023-02-03 01:28 UTC, jcoyne approved these changes

2023-02-03 22:05 UTC, marlo-longley commented
The BL commit that the AL tests start failing on: https://github.com/projectblacklight/blacklight/commit/3e4a46f19bdb285af3ad75e43c56de85854a67ad. This commit was included in beta5.
Before that, all the way down to BL beta1, the tests in AL pass.

2023-02-07 18:26 UTC, merged